"""
프로젝트 설정 및 상수 정의
"""

# 시리얼 통신 설정
SERIAL_BAUDRATE = 115200
SERIAL_TIMEOUT = 2
SERIAL_BYTESIZE = 8
SERIAL_PARITY = 'N'  # None
SERIAL_STOPBITS = 1

# AT 명령어
AT_CMD_VMAC = "AT+VMAC"
AT_CMD_SCFG = "AT+SCFG"
AT_CMD_RBOT = "AT+RBOT"

# 타임아웃 및 대기 시간 (초)
WAIT_TIME_SHORT = 2
WAIT_TIME_NORMAL = 3
WAIT_TIME_LONG = 5
READ_TIMEOUT = 1
